config/routes.rb
Rails.application.routes.draw do
    resources :users
    resources :tweets
    resources :likes
    
    #root 'tops#main'
    #root 'users#index'
    root 'tweets#index'
    #root 'tops#login_form'
    
    get 'tops/main'
    post 'tops/login'
    get 'tops/logout'
    #root 'top#main'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes
    has_many :like_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tweets
    has_many :likes
    has_many :like_tweets, through: :likes, source: :tweet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create 
    tweet = Tweet.find(params[:tweet_id])
    user = User.find_by(uid: session[:login_uid])
    user.like_tweets << tweet
    redirect_to root_path
  end

  def destroy
    tweet = Tweet.find(params[:id])
    user = User.find_by(uid: session[:login_uid])
    tweet.likes.find_by(user_id: user.id).destroy
    redirect_to root_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

    def main
        render 'login'
    end
    
    def login
        user = User.find_by(uid: params[:uid])
        if user and BCrypt::Password.new(user.pass) == params[:pass]
            session[:login_uid] = user.uid
            redirect_to root_path
        else
            render 'login'
        end
    end
    
    def logout
        session.delete(:login_uid)
        redirect_to root_path
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
        @tweets = Tweet.all
    end
    def new
        @tweet = Tweet.new
    end
    def create
        user = User.find_by(uid: session[:login_uid])
        @tweet = Tweet.new(user_id: user.id, message: params[:tweet][:message])
        if @tweet.save
            flash[:notice] = '1件ツイートしました'
            redirect_to root_path
        else
            render 'new'
        end
    end
    def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        flash[:notice] = 'ツイートを削除しました'
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    def new
        @user = User.new
    end
    def create 
    @user = User.new(uid: params[:user][:uid],pass: params[:user][:pass])
    if @user.valid? 
      @user.pass = BCrypt::Password.create(params[:user][:pass])
      @user.save
      redirect_to users_path
    else
      render 'new'
    end
    end
  
    def destroy
        user = User.find(params[:id])
        user.destroy
        flash[:notice] = 'ツイートを削除しました'
        redirect_to users_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tops/login.html.erb
<%= form_tag tops_login_path, method: :post do %>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %>
    <%= submit_tag 'ログイン' %>
<% end %>

app/views/tops/login_form.html.erb
<%= form_tag '/tops/login', method: :post do %>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %>
    <%= submit_tag 'ログイン' %>
<% end %>

app/views/tweets/index.html.erb
<% @tweets.each do |e| %>
  <p>
    <%= e.message %>
    <% if session[:login_uid] %>
      <%= link_to '削除', tweet_path(e), method: :delete %>
      <% if e.likes.count > 0 %>
        <%= link_to '♥', like_path(e), method: :delete %>
      <% else %>
        <%= link_to '♡', likes_path(tweet_id: e.id), method: :post %>
      <% end %>
    <% end %>
    </p>
<% end %>

<p> 
<% if session[:login_uid] %>
  <%= link_to 'ツイートする', new_tweet_path %>
<% end %>
</p>

<p>
<% if session[:login_uid] %>
  <%= link_to 'ログアウト', tops_logout_path %>
<% else %>
  <%= link_to 'ログイン', tops_main_path %>
<% end %>
</p>

<p>
  <%= link_to 'ユーザ一覧', users_path %>
</p>

app/views/tweets/new.html.erb
<% if @tweet.errors.present? %>
    <h3>エラーがあります。</h3>
    <ul>
    <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>

<%= form_for @tweet, url: {action: :create} do |f| %>
  <%= f.label :message, 'メッセージ' %> 
  <%= f.text_field :message %> 
  <%= f.submit 'ツイートする' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |e| %>
    <p>
        <b>ID:</b> <%= e.uid %>
        <b>pass:</b> <%= e.pass %>
        <%= link_to '削除', user_path(e), method: :delete %>
    </p>
<% end %>


<p><%= link_to 'ユーザー登録', new_user_path %></p>

<p><%= link_to 'ツイート一覧', tweets_path %></p>

app/views/users/new.html.erb
<%= form_for @user, url: {action: :create} do |f| %>
  <%= f.label :uid, 'uid' %> 
  <%= f.text_field :uid %> 
  <%= f.label :pass, 'pass' %> 
  <%= f.password_field :pass %> 
  <%= f.submit '登録' %>
<% end %>